#-------------------------------
# General Site Settings
baseURL = "http://collegegrind.org/"
languageCode = "en-us"
title = "CG"
googleAnalytics = "G-WLTEPDRMZK" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 7

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 7 # Sets the number of items per page for older versions.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

#  [[menu.main]]
#    identifier = "authors"
#    name = "Authors"
#    url = "/authors/"
#    weight = 3

#  [[menu.main]]
#    identifier = "videos"
#    name = "Videos"
#    url = "/videos/"
#    weight = 3
#    hasChildren = true

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
    hasChildren = true

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5
    hasChildren = true

#      [[menu.main]]
#        parent = "Pages"
#        name = "About"
#        url = "/about/"
#        weight = 1

#      [[menu.main]]
#        parent = "Pages"
#        name = "Contact"
#        url = "/contact/"
#        weight = 2

#      [[menu.main]]
#        parent = "Pages"
#        name = "Elements"
#        url = "/elements/"
#        weight = 3

    # Footer Menu
    [[menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

    [[menu.footer]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 2

    [[menu.footer]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 3

#    [[menu.footer]]
#      identifier = "elements"
#      name = "Elements"
#      url = "/elements/"
#      weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  logo_dark = ""
  description = "The College Grind is dedicatd to writing down the unwritten rules of higher education."
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Hero Settings
[params.hero]
  enable = true
  hero__title = "The College Grind"
  hero__description = "Writing down the unwritten rules of higher education."
  hero__image = "" # You can add hero image. For example "/images/06.jpg"


#-------------------------------
# Blog Section Settings
[params.blog]
  enable = true
  blog__title = "Latest Posts"
  blog__description = ""


#-------------------------------
# Videos Section Settings
[params.videos]
  enable = false
  videos__title = "Latest Videos"
  videos__description = ""


#-------------------------------
# Tag Section Settings
[params.tag]
  enable = false
  tag = "travel" # To display the tag section, specify your favorite tag.


#-------------------------------
# Author Section Settings
[params.author_section]
  enable = false
  author__section__title = "Hello, my name is Alena. I’m reviewer and content creator."
  author__section__description = "I’m a published content creator, brand copywriter, photographer, and social media content creator and manager. I help brands connect with their customers by developing engaging content that entertains, educates, and offers value to their audience."
  aurhor__section__button__text = "More About Me"
  aurhor__section__button__link = "/about"
  author__section__big__image = "https://placehold.co/1200x800"
  author__section__small__image = "https://placehold.co/1200x800"
  author__section__image__alt = "Alena Curtis"


# Newsletter
[params.mailchimp]
  enable = true
  mailchimp__title = "Join The Grind"
  mailchimp__description = "Occasional emails with useful insights on learning, discipline, and making progress when school gets hard."
  mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp__input__text = "Your email address"
  mailchimp__button__text = "Subscribe"
  mailchimp__background__image = "https://placehold.co/1920x1080"


#-------------------------------
# Footer Settings
[params.footer]
  footer__description = "Writing down the unwritten rules of higher education."

# Social Links
#[[params.social]]
#  icon = "fa-brands fa-x-twitter"
#  name = "Twitter"
#  link = "https://twitter.com"

#[[params.social]]
#  icon = "fa-brands fa-facebook"
#  name = "Facebook"
#  link = "https://facebook.com"

#[[params.social]]
#  icon = "fa-brands fa-codepen"
#  name = "Codepen"
#  link = "https://codepen.io"

#[[params.social]]
#  icon = "fa-brands fa-pinterest"
#  name = "Pinterest"
#  link = "https://pinterest.com"

#[[params.social]]
#  icon = "fa-brands fa-vimeo-v"
#  name = "Vimeo"
#  link = "https://vimeo.com"

# Example of adding a new link to the footer section:
# [[params.social]]
#   icon = "fa-brands fa-mastodon"
#   name = "Mastodon"
#   link = "https://mastodon.social"

# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
[params.contact]
  form_id = "your@email.com" # Add your form_id

  # NOTE
  # Mria comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
[params.disqus]
  enable = false
  disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    ordered = false
    endLevel = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
